version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::533267287698:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-ChmOpbm8ebW9"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::533267287698:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-ZVpZWJyhAlSa"
cloudformation_execution_role = "arn:aws:iam::533267287698:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-zVOXPln0c7CD"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-ucbeki6jx02x"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::533267287698:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-oPjrMbBSXSDp"
cloudformation_execution_role = "arn:aws:iam::533267287698:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-huPcxERSM2C8"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-pjbhirs5tscf"
image_repository = ""
region = "us-east-1"
